### ISSUE TITLE
m8c closing immediately after opening

### ISSUE THREAD

**Issue by nullrygar** [jasonporritt/rg351_m8c#6]
Hi There! 

Just picked up a rg351mp and tried installing to check this out.  I am fairly new to this sort of thing, so this is most likely me doing something wrong.  

I went through all of the setup multiple times, and everything seemed to be a success.  But, when i try launching M8, m8_performance, pulse etc, I get an arkos screen for a second and then it kicks me back to the menu.

Any suggestions?

**Comment by smootalicious** [comment]
What was the actual problem and how did you solve it?

**Comment by comejar** [comment]
Just thought I'd comment on this considering there was never a reply from original poster

I was having this issue and it was a simple thing to fix it after hours of reinstalling everything multiple times that made me feel a bit dumb

I realised I was just extracting the zip directly to the ports folder so it was "rg351_m8c" going in there rather than just putting the "M8" folder within the zip into there

Now working fine
